const D=[["Neon Skyline","Aria Vale","Night Drive","Synthwave","energetic,focus",212],["Slow Rain","Mira Sol","Quiet Hours","Lo-fi","chill,sad,focus",185],["Golden Hour","Juno Park","Sunday Sun","Pop","happy,romantic",198],["Midnight Bloom","Kavi","Petals","R&B","romantic,chill",224],["Run It Up","Blaze Harlow","Overdrive","Hip-Hop","energetic,angry,workout",176],["Hollow Streets","Ember Road","Static Hearts","Rock","sad,angry",241],["Dance Till Dawn","Luna Vox","Afterglow","Dance","happy,party,energetic",203],["Paper Boats","Oli Reed","Tiny Oceans","Indie","chill,happy",190],["Deep Focus 01","Nomad Keys","Study Waves","Ambient","focus,chill",260],["Broken Compass","Ember Road","Static Hearts","Rock","sad",218],["Sunrise Mantra","Kavi","Petals","R&B","happy,chill",207],["Voltage","Blaze Harlow","Overdrive","Hip-Hop","workout,energetic,party",168],["Blue Tuesday","Mira Sol","Quiet Hours","Lo-fi","sad,chill",172],["City Lights Love","Juno Park","Sunday Sun","Pop","romantic,happy",195],["Afterparty Heart","Luna Vox","Afterglow","Dance","party,romantic",210],["Wild Fields","Oli Reed","Tiny Oceans","Indie","happy,energetic",201]];
const FB=D.map((d,i)=>({id:i,t:d[0],a:d[1],al:d[2],g:d[3],m:d[4].split(','),d:d[5]}));
let S=[],M={},LIVE=false;
const ing=s=>{if(!M[s.id]){M[s.id]=s;S.push(s)}else s.m.forEach(x=>{if(!M[s.id].m.includes(x))M[s.id].m.push(x)})};
const QS=[["happy pop hits","happy"],["sad songs","sad"],["chill lofi","chill"],["focus instrumental","focus"],["workout hip hop","energetic"],["love songs","romantic"],["party dance","party"],["rock anthem","angry"]];
async function jf(u){const c=new AbortController(),h=setTimeout(()=>c.abort(),7000);try{const r=await fetch(u,{signal:c.signal});return await r.json()}finally{clearTimeout(h)}}
const IT=(q,n,m)=>jf(`https://itunes.apple.com/search?term=${encodeURIComponent(q)}&media=music&entity=song&limit=${n}`).then(j=>j.results.filter(r=>r.previewUrl).map(r=>({id:r.trackId,t:r.trackName,a:r.artistName,al:r.collectionName||'Single',g:r.primaryGenreName||'Music',m:[...m],d:30,p:r.previewUrl,img:(r.artworkUrl100||'').replace('100x100','400x400'),rd:r.releaseDate||''})));
const AR=()=>[...new Set(S.map(s=>s.a))],AL=()=>[...new Set(S.map(s=>s.al))];
const LY={happy:["The sky is wide and so are we","Sunlight spilling on the street","Every step becomes a song","Nothing here can bring me down","Sing it loud, just let it be"],sad:["Rain is writing on the glass","Empty rooms and fading light","I keep your echo close tonight","Even quiet hurts sometimes","Morning will find me anyway"],chill:["Slow the world down, breathe in deep","Drifting where the water goes","No place left that I must be","Let the evening carry me","Soft and easy, let it flow"],energetic:["Heartbeat loud, the lights go up","Feel the thunder in my chest","Nothing stops us, run it out","Higher now, we own the night","Louder, faster, don't look back"],romantic:["Your voice is home to me","Hold my hand beneath the stars","Every street leads back to you","Stay a little longer, love","Two hearts, one slow-burning light"],focus:["Clear the noise and find the line","One thing at a time","Steady breath, a steady mind","Let the hours melt away","Deep in the flow, stay here"]};
const AL_={party:'energetic',workout:'energetic',angry:'sad'};
const lyr=s=>["♪ "+s.t+" ♪",...(LY[AL_[s.m[0]]||s.m[0]]||LY.chill),"♪ "+s.a+" ♪"];
const hue=s=>{let h=0;for(const c of s)h=(h*31+c.charCodeAt(0))%360;return h};
const cov=(s,c='')=>{const gr=`linear-gradient(135deg,hsl(${hue(s.al)} 60% 36%),hsl(${(hue(s.al)+70)%360} 70% 14%))`;return`<div class="cv ${c}" style="background:${s.img?`url('${s.img}') center/cover,`:''}${gr}">${s.img?'':s.t[0]}</div>`};
const $=x=>document.querySelector(x),fm=x=>Math.floor(x/60)+":"+String(x%60).padStart(2,'0');
let st={likes:{s:[],al:[],ar:[]},pl:[{id:1,n:"My First Fly",s:[0,3,7]}],recent:[],plays:{},nid:2};
const loadSt=()=>{try{const r=localStorage.getItem(SK);if(r)st=JSON.parse(r)}catch(e){}};
const save=()=>{try{st.lib=LIVE?M:undefined;localStorage.setItem(SK,JSON.stringify(st))}catch(e){}};
let q=[],qi=-1,playing=false,t=0,shuf=false,rep=0,view='home',arg=null,L={},lenis=null,lv=null,SK='fly';
const cur=()=>M[q[qi]];
const au=new Audio();let aid=null;au.onended=()=>next();
function sa(ch){const s=cur();if(!s||!s.p){au.pause();return}if(aid!=s.id){au.src=s.p;aid=s.id}else if(ch&&t==0)au.currentTime=0;if(playing)au.play().catch(()=>{});else au.pause()}
function seekTo(v){t=v;const s=cur();if(s&&s.p)au.currentTime=v;upd()}
function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.h);toast.h=setTimeout(()=>e.classList.remove('show'),2200)}
function play(list,i){q=[...list];qi=i;t=0;playing=true;const s=cur();st.recent=[s.id,...st.recent.filter(x=>x!==s.id)].slice(0,8);st.plays[s.g]=(st.plays[s.g]||0)+1;save();upd(true)}
const pl=(k,i)=>{play(L[k],i);if(view=='home')draw()};
function tog(){if(qi<0){const r=recs();L.r=r;return play(r,0)}playing=!playing;upd()}
function next(){if(qi<0)return;if(rep==2)t=0;else if(shuf&&q.length>1){let n;do n=Math.floor(Math.random()*q.length);while(n==qi);qi=n;t=0;bump()}else if(qi<q.length-1){qi++;t=0;bump()}else if(rep==1){qi=0;t=0;bump()}else{playing=false;t=0}upd(true)}
function bump(){const s=cur();st.recent=[s.id,...st.recent.filter(x=>x!==s.id)].slice(0,8);st.plays[s.g]=(st.plays[s.g]||0)+1;save()}
function prev(){if(qi<0)return;if(t>3||qi==0)t=0;else{qi--;t=0}upd(true)}
setInterval(()=>{if(playing&&qi>=0){const s=cur();if(s.p){t=Math.floor(au.currentTime);upd()}else{t++;if(t>=s.d)next();else upd()}}},1000);
const liked=id=>st.likes.s.includes(id);
function tl(id){const a=st.likes.s,i=a.indexOf(id);i<0?(a.push(id),toast("Saved to Liked Songs")):a.splice(i,1);save();upd();draw()}
function tk(k,n){const a=st.likes[k],i=a.indexOf(n);i<0?a.push(n):a.splice(i,1);save();draw()}
function aq(id){if(qi<0){q=[id];qi=0;t=0;playing=true;upd(true)}else{q.push(id);toast("Added to queue")}upd()}
function upd(ch){const s=cur();sa(ch);
$('#pi').innerHTML=s?`${cov(s)}<div><b>${s.t}</b><small>${s.a}</small></div><button class="ib ${liked(s.id)?'on':''}" onclick="event.stopPropagation();tl(${s.id})">${liked(s.id)?'♥':'♡'}</button>`:'<small>Pick a song to start flying</small>';
$('#pp').textContent=playing?'❚❚':'▶';$('#sh').classList.toggle('on',shuf);$('#rp').classList.toggle('on',rep>0);$('#rp').textContent=rep==2?'↻¹':'↻';
const sk=$('#sk');if(s){sk.max=s.d;sk.value=t;$('#t0').textContent=fm(t);$('#t1').textContent=fm(s.d)}
$('#np').classList.toggle('pulse',playing);
if(s&&$('#np').classList.contains('show')){if(ch||!$('#ly').children.length){$('#npc').innerHTML=cov(s)+`<h1 style="margin-top:18px">${s.t}</h1><p class="sm">${s.a} · ${s.al}</p><div style="margin-top:10px"><button class="btn" onclick="tog()">${playing?'Pause':'Play'}</button></div>`;$('#ly').innerHTML=lyr(s).map(l=>`<p>${l}</p>`).join('')}
else $('#npc').querySelector('.btn').textContent=playing?'Pause':'Play';
const ls=lyr(s),k=Math.min(ls.length-1,Math.floor(t/s.d*ls.length)),ps=$('#ly').children;[...ps].forEach((p,i)=>{p.className=i==k?'on':i<k?'past':''});const a=ps[k];if(a)$('#ly').scrollTop=a.offsetTop-$('#ly').clientHeight/2+a.clientHeight/2}
if(ch){document.querySelectorAll('.row').forEach(r=>r.classList.toggle('cur',+r.dataset.id===(s&&s.id)));if($('#qp').classList.contains('show'))qr()}}
function fs(o){if(o&&qi<0)return toast("Play a song first");$('#np').classList.toggle('show',!!o);if(o){$('#ly').innerHTML='';upd(true)}}
function qo(o){$('#qp').classList.toggle('show',!!o);if(o)qr()}
function qr(){$('#qb').innerHTML=`<h2 style="margin-top:0">Queue</h2>`+(qi<0?'<p class="sm">Nothing queued yet.</p>':`<p class="sm">Now playing</p>${row(cur().id,'',0)}<p class="sm" style="margin:14px 0 4px">Next up</p>`+(q.slice(qi+1).map((id,j)=>`<div class="row">${mini(id)}<button class="ib" onclick="qm(${qi+1+j},-1)">↑</button><button class="ib" onclick="qm(${qi+1+j},1)">↓</button><button class="ib" onclick="qd(${qi+1+j})">✕</button></div>`).join('')||'<p class="sm">Queue is empty.</p>'))+`<h2>Add songs</h2>`+S.filter(s=>!q.includes(s.id)).slice(0,6).map(s=>`<div class="row">${mini(s.id)}<button class="ib" onclick="aq(${s.id});qr()">＋</button></div>`).join('')}
const mini=id=>{const s=M[id];return`<div class="in" style="cursor:default">${cov(s)}<div><b>${s.t}</b><small>${s.a}</small></div></div>`};
function qm(i,d){const j=i+d;if(j<=qi||j>=q.length)return;[q[i],q[j]]=[q[j],q[i]];qr()}
function qd(i){q.splice(i,1);qr()}
function row(id,k,i,extra=''){const s=M[id];return`<div class="row ${cur()&&cur().id==id?'cur':''}" data-id="${id}"><div class="in" onclick="pl('${k}',${i})">${cov(s)}<div><b>${s.t}</b><small>${s.a} · ${s.al}</small></div></div><button class="ib ${liked(id)?'on':''}" onclick="tl(${id})">${liked(id)?'♥':'♡'}</button><button class="ib" onclick="aq(${id})" title="Add to queue">＋</button><button class="ib" onclick="ap(${id})" title="Add to playlist">☰</button>${extra}</div>`}
const rows=(k,ids)=>{L[k]=ids;return ids.map((id,i)=>row(id,k,i)).join('')};
const cards=(k,ids,nw)=>{L[k]=ids;return`<div class="sc">`+ids.map((id,i)=>{const s=M[id];return`<button class="card" onclick="pl('${k}',${i})">${cov(s)}<b>${s.t}</b><small>${nw?'<span class="tag">NEW</span> ':''}${s.a}</small></button>`}).join('')+`</div>`};
function modal(h){$('#mb').innerHTML=h;$('#md').classList.add('show')}const mc=()=>$('#md').classList.remove('show');
$('#md').onclick=e=>{if(e.target.id=='md')mc()};
function ap(id){modal(`<h2 style="margin-top:0">Add to playlist</h2>`+st.pl.map(p=>`<div class="row"><button class="in" onclick="addTo(${p.id},${id})"><b>${p.n}</b></button></div>`).join('')+`<div style="margin-top:12px"><button class="btn o" onclick="newPl(${id})">＋ New playlist</button></div>`)}
function addTo(pid,id){const p=st.pl.find(x=>x.id==pid);if(!p.s.includes(id))p.s.push(id);save();mc();toast("Added to "+p.n);draw()}
function newPl(id,name,ids){const n=name||prompt("Playlist name","My Playlist");if(!n)return;const p={id:st.nid++,n,s:ids?[...ids]:id!=null?[id]:[]};st.pl.push(p);save();mc();toast("Created "+n);if(name)go('pl',p.id);else draw()}
function taste(){const g={};S.forEach(s=>{});st.likes.s.forEach(i=>g[M[i].g]=(g[M[i].g]||0)+3);for(const k in st.plays)g[k]=(g[k]||0)+st.plays[k];return g}
function score(s){const g=taste();return(g[s.g]||0)+(st.likes.ar.includes(s.a)?4:0)+(st.likes.al.includes(s.al)?3:0)+(liked(s.id)?1:0)}
const hasTaste=()=>Object.keys(taste()).length>0;
function recs(n=8){return hasTaste()?[...S].sort((a,b)=>score(b)-score(a)).slice(0,n).map(s=>s.id):trend().slice(0,n)}
const trend=()=>{const a=S.map(s=>s.id),o=[],n=8,k=Math.ceil(a.length/n);for(let j=0;j<k;j++)for(let i=0;i<n;i++){const v=a[i*k+j];if(v!=null)o.push(v)}return o};
const NEW=()=>[...S].sort((a,b)=>(b.rd||'').localeCompare(a.rd||'')||b.id-a.id).slice(0,6).map(s=>s.id);
const MK={happy:"happy great good joy excited fun smile cheerful 😀 😊",sad:"sad down lonely cry blue heartbroken depressed low upset 😢 😞",chill:"chill relax calm tired sleepy peace slow 😌",focus:"focus study work concentrate code read exam",energetic:"energy gym workout run pump hype motivated 💪",romantic:"love romantic date miss crush 😍 ❤",party:"party dance friends celebrate weekend",angry:"angry mad rage frustrated annoyed 😡"};
let mood=null,mtxt='';
function detect(txt){const w=txt.toLowerCase();let best=null,bs=0;for(const m in MK){const sc=MK[m].split(' ').filter(k=>w.includes(k)).length;if(sc>bs){bs=sc;best=m}}return best}
function setMood(m){mood=m;draw()}
function doDetect(){mtxt=$('#mt').value;const m=detect(mtxt);if(!m){toast("Couldn't read that mood, pick one below");return}mood=m;draw()}
function share(id){const p=st.pl.find(x=>x.id==id),tx=`Listen to my Fly playlist "${p.n}": `+p.s.map(i=>M[i].t).join(', ');(navigator.clipboard?navigator.clipboard.writeText(tx):Promise.reject()).then(()=>toast("Playlist link text copied"),()=>modal(`<h2 style="margin-top:0">Share</h2><p>${tx}</p><br><button class="btn" onclick="mc()">Done</button>`))}
function pm(id,i,d){const a=st.pl.find(x=>x.id==id).s,j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];save();draw()}
function prm(id,i){st.pl.find(x=>x.id==id).s.splice(i,1);save();draw()}
function ren(id){const p=st.pl.find(x=>x.id==id),n=prompt("Rename playlist",p.n);if(n){p.n=n;save();draw()}}
function del(id){if(confirm("Delete this playlist?")){st.pl=st.pl.filter(x=>x.id!=id);save();go('library')}}
function go(v,a){view=v;arg=a;draw()}
function rs(v){v=v.trim().toLowerCase();const r=$('#res');if(!v){r.innerHTML='<p class="sm">Search songs, artists, albums, genres, playlists or lyrics.</p>';return}
const ms=S.filter(s=>[s.t,s.a,s.al,s.g].some(x=>x.toLowerCase().includes(v))||lyr(s).some(l=>l.toLowerCase().includes(v))),ars=AR().filter(a=>a.toLowerCase().includes(v)),als=AL().filter(a=>a.toLowerCase().includes(v)),pls=st.pl.filter(p=>p.n.toLowerCase().includes(v));
r.innerHTML=(ms.length?`<h2>Songs</h2>`+rows('s',ms.map(s=>s.id)):'')+(ars.length?`<h2>Artists</h2><div class="chips">`+ars.map(a=>`<span class="chip">${a} <button class="ib ${st.likes.ar.includes(a)?'on':''}" onclick="tk('ar','${a}');doSearch($('#si').value)">♥</button></span>`).join('')+'</div>':'')+(als.length?`<h2>Albums</h2><div class="chips">`+als.map(a=>`<span class="chip">${a} <button class="ib ${st.likes.al.includes(a)?'on':''}" onclick="tk('al','${a}');doSearch($('#si').value)">♥</button></span>`).join('')+'</div>':'')+(pls.length?`<h2>Playlists</h2>`+pls.map(p=>`<div class="row"><button class="in" onclick="go('pl',${p.id})"><b>${p.n}</b><small>${p.s.length} songs</small></button></div>`).join(''):'')||'<p class="sm">No matches. Try another word.</p>'}
function draw(){document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('on',n.dataset.v==view));const sc=$('#main'),m=$('#mc'),top=lv==view?sc.scrollTop:0;let h='';
if(view=='home'){const hr=new Date().getHours(),gr=hr<12?'Good morning':hr<18?'Good afternoon':'Good evening';
h=`<h1>${gr}</h1><div class="hero"><div style="font-size:30px">✦</div><p><b>${hasTaste()?'Made for you':'Fly AI is learning your taste'}</b><br><span class="sm">${hasTaste()?'Your picks, based on what you play and like.':'Play and like songs to get picks made just for you.'}</span></p><button class="btn" onclick="go('mood')">Open Fly AI</button></div>`+(LIVE?'':'<p class="sm">Showing sample songs. Real songs and 30-second previews load when Fly runs from a file on your computer.</p>')+(st.recent.length?`<h2>Recently played</h2>`+cards('rc',st.recent):'')+`<h2>${hasTaste()?'Recommended for you':'Recommended songs'}</h2>`+cards('rec',recs())+`<h2>New releases</h2>`+cards('nw',NEW(),1)+`<h2>Trending now</h2>`+rows('tr',trend().slice(0,6))}
else if(view=='search'){const v=$('#si')?$('#si').value:'';h=`<h1>Search</h1><div style="margin:14px 0"><input type="text" id="si" placeholder="What do you want to hear?" oninput="doSearch(this.value)" value="${v}"></div><div id="res"></div>`}
else if(view=='library'){h=`<h1>Your Library</h1><div style="margin:14px 0"><button class="btn" onclick="newPl()">＋ Create playlist</button></div><h2>Playlists</h2>`+st.pl.map(p=>`<div class="row"><button class="in" onclick="go('pl',${p.id})">${p.s.length?cov(M[p.s[0]]):'<div class="cv" style="background:var(--p2)">♪</div>'}<div><b>${p.n}</b><small>${p.s.length} songs</small></div></button></div>`).join('')+`<h2>Liked Songs</h2>`+(st.likes.s.length?rows('ls',st.likes.s):'<p class="sm">Tap ♡ on any song to save it here.</p>')+`<h2>Liked albums</h2><div class="chips">`+st.likes.al.map(a=>`<button class="chip ${st.likes.al.includes(a)?'on':''}" onclick="tk('al','${a}')">${a}</button>`).join('')+`</div><h2>Liked artists</h2><div class="chips">`+st.likes.ar.map(a=>`<button class="chip ${st.likes.ar.includes(a)?'on':''}" onclick="tk('ar','${a}')">${a}</button>`).join('')+`</div>`}
else if(view=='pl'){const p=st.pl.find(x=>x.id==arg);if(!p)return go('library');L.p=p.s;h=`<h1>${p.n}</h1><p class="sm">${p.s.length} songs</p><div style="display:flex;gap:8px;flex-wrap:wrap;margin:14px 0"><button class="btn" onclick="p.s.length&&pl('p',0)">▶ Play</button><button class="btn o" onclick="ren(${p.id})">Rename</button><button class="btn o" onclick="share(${p.id})">Share</button><button class="btn o" onclick="del(${p.id})">Delete</button></div>`.replace('p.s.length&&pl',p.s.length?'pl':'toast(\'Empty playlist\');0&&pl')+(p.s.map((id,i)=>row(id,'p',i,`<button class="ib" onclick="pm(${p.id},${i},-1)">↑</button><button class="ib" onclick="pm(${p.id},${i},1)">↓</button><button class="ib" onclick="prm(${p.id},${i})">✕</button>`)).join('')||'<p class="sm">Empty. Add songs with the ☰ button on any track.</p>')}
else if(view=='mood'){const g=taste(),mx=Math.max(1,...Object.values(g)),tg=Object.entries(g).sort((a,b)=>b[1]-a[1]).slice(0,5);
h=`<h1>✦ Fly AI</h1><h2>How are you feeling?</h2><div style="display:flex;gap:8px"><input type="text" id="mt" placeholder="e.g. tired after work, need to relax" value="${mtxt}" onkeydown="if(event.key=='Enter')doDetect()"><button class="btn" onclick="doDetect()">Detect</button></div><div class="chips">`+Object.keys(MK).map(m=>`<button class="chip ${mood==m?'on':''}" onclick="setMood('${m}')">${m}</button>`).join('')+`</div>`;
if(mood){const ids=S.filter(s=>s.m.includes(mood)).sort((a,b)=>score(b)-score(a)).map(s=>s.id);h+=`<h2>Feeling ${mood}</h2><p class="sm">Songs tuned to this mood, ordered by your taste.</p><div style="margin:10px 0;display:flex;gap:8px"><button class="btn" onclick="pl('md',0)">▶ Play</button><button class="btn o" onclick="newPl(null,'Fly ${mood} mix',L.md)">Save as playlist</button></div>`+rows('md',ids)}
h+=`<h2>Your taste profile</h2>`+(tg.length?tg.map(([k,v])=>`<div class="row"><span style="width:90px">${k}</span><div class="bar"><i style="width:${v/mx*100}%"></i></div></div>`).join(''):'<p class="sm">No data yet. Play or like a few songs and Fly AI will build your profile.</p>')+`<h2>Made for you</h2><div style="margin:10px 0"><button class="btn o" onclick="newPl(null,'Made for you',recs(8))">Save as playlist</button></div>`+rows('mfy',recs(8))}
m.innerHTML=h;if(lv!=view){m.classList.remove('in');void m.offsetWidth;m.classList.add('in')}lv=view;if(lenis)lenis.scrollTo(top,{immediate:true});else sc.scrollTop=top;if(view=='search')doSearch($('#si').value)}
let sdb;function doSearch(v){rs(v);if(!LIVE||v.trim().length<3)return;clearTimeout(sdb);sdb=setTimeout(async()=>{try{const r=await IT(v.trim(),15,[]);const n=S.length;r.forEach(ing);if(S.length>n){save();if($('#si')&&$('#si').value==v)rs(v)}}catch(e){}},450)}
let TH=null,lw=0,lh=0;
function initGL(){if(TH||!window.THREE)return;try{const R=new THREE.WebGLRenderer({canvas:$('#gl'),alpha:true,antialias:true});R.setPixelRatio(Math.min(devicePixelRatio,2));const sc=new THREE.Scene(),cam=new THREE.PerspectiveCamera(50,1,.1,50);cam.position.z=7;
const geo=new THREE.IcosahedronGeometry(2.1,12),base=geo.attributes.position.array.slice(),pts=new THREE.Points(geo,new THREE.PointsMaterial({color:0x2bdc6b,size:.03,transparent:true,opacity:.85,blending:THREE.AdditiveBlending,depthWrite:false}));sc.add(pts);
const rg=new THREE.BufferGeometry(),N=900,pa=new Float32Array(N*3);for(let i=0;i<N;i++){const a=Math.random()*6.283,r=3.2+Math.random()*1.4;pa[i*3]=Math.cos(a)*r;pa[i*3+1]=(Math.random()-.5)*.6;pa[i*3+2]=Math.sin(a)*r}rg.setAttribute('position',new THREE.BufferAttribute(pa,3));const ring=new THREE.Points(rg,new THREE.PointsMaterial({color:0x8b948f,size:.03,transparent:true,opacity:.6}));ring.rotation.x=.5;sc.add(ring);TH={R,sc,cam,geo,base,pts,ring,en:.15}}catch(e){TH=null}}
function glf(tm){const T=TH;if(!T||!$('#np').classList.contains('show'))return;const w=innerWidth,h=innerHeight;if(w!=lw||h!=lh){lw=w;lh=h;T.R.setSize(w,h,false);T.cam.aspect=w/h;T.cam.updateProjectionMatrix()}
const tt=tm/1000;T.en+=((playing?1:.15)-T.en)*.04;const a=T.geo.attributes.position.array,b=T.base;for(let i=0;i<a.length;i+=3){const x=b[i],y=b[i+1],z=b[i+2],k=1+T.en*(.16*Math.sin(x*1.8+tt*2.2)+.12*Math.sin(y*2.4+tt*1.7)+.1*Math.sin(z*3+tt*2.9))+.03*Math.sin(tt+x);a[i]=x*k;a[i+1]=y*k;a[i+2]=z*k}
T.geo.attributes.position.needsUpdate=true;T.pts.rotation.y=tt*.15;T.pts.rotation.x=tt*.07;T.ring.rotation.y=-tt*.1;T.pts.position.x=T.ring.position.x=w>760?2.6:0;T.pts.scale.setScalar(1+T.en*.05*Math.sin(tt*6));T.R.render(T.sc,T.cam)}
function loop(tm){if(lenis)lenis.raf(tm);glf(tm);const s=cur(),k=$('#sk');if(playing&&s&&s.p&&document.activeElement!==k)k.value=au.currentTime;requestAnimationFrame(loop)}
async function boot(){$('#mc').innerHTML='<p class="sm" style="padding:40px 0">Loading songs…</p>';
try{const r=await Promise.all(QS.map(([q,m])=>IT(q,12,[m])));r.forEach(a=>a.forEach(ing));LIVE=S.length>10}catch(e){LIVE=false}
if(LIVE)SK='fly-live';else{S=[];M={};FB.forEach(ing)}
loadSt();if(LIVE&&st.lib)for(const k in st.lib)ing(st.lib[k]);
st.likes.s=st.likes.s.filter(i=>M[i]);st.recent=st.recent.filter(i=>M[i]);st.pl.forEach(p=>p.s=p.s.filter(i=>M[i]));
if(LIVE&&st.pl[0]&&st.pl[0].id==1&&!st.pl[0].s.length)st.pl[0].s=S.slice(0,3).map(s=>s.id);
try{if(window.Lenis)lenis=new Lenis({wrapper:$('#main'),content:$('#mc'),duration:1.15,easing:x=>Math.min(1,1.001-Math.pow(2,-10*x))})}catch(e){}
initGL();draw();upd();requestAnimationFrame(loop)}
boot();